/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheImage: typeof import('./src/components/TheImage.vue')['default']
    TheImgContainer: typeof import('./src/components/TheImgContainer.vue')['default']
    TheProxy: typeof import('./src/components/TheProxy.vue')['default']
  }
}
